### PR TITLE
refactor games

### LINKED ISSUE #38: Refactore games
This part is common in every HandleDart method, it should be refactored

```java
    if game.state.Ongoing == common.ONHOLD {
		error = errors.New("Game is on hold and not ready to handle darts")
		return
	}

	if game.state.Ongoing == common.READY {
		// first dart starts the game
		err := game.Start()
		if err != nil {
			error = err
			return
		}
	}

	if game.state.Ongoing != common.PLAYING {
		error = errors.New("Game is not started or is ended")
		return
	}

	if !sector.IsValid() {
		log.WithFields(log.Fields{"sector": sector}).Error("Invalid sector")
		error = errors.New("Sector is not a valid one")
		return
	}
```

### PR DESCRIPTION
**Pull request by ggerbaud**
fix #38

### CODE REVIEW

**Comment by mathieu-pousse** [comment]
Hum... hum...

Why not to bind the common* to a AGame object and nothing else is needed for the games that do not override the method.

As for AGame.BoardHasLeft

And if needed, the game.AGame.theAncientCommonMethodNameGoesHere()

**Comment by erwannT** [comment]
LGTM

**Comment by mathieu-pousse** [comment]
prefer AGame pointer in the common methods instead of copying the values

**Comment by mathieu-pousse** [comment]
lgtm

**Pull request merged**
